# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: N:/ECE540/540FinalProject/ece_540_project_4_v1.srcs/sources_1/ip/world_map/world_map.xci
# IP: The module: 'world_map' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: n:/ECE540/540FinalProject/ece_540_project_4_v1.srcs/sources_1/ip/world_map/world_map_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'world_map'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: N:/ECE540/540FinalProject/ece_540_project_4_v1.srcs/sources_1/ip/world_map/world_map.xci
# IP: The module: 'world_map' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: n:/ECE540/540FinalProject/ece_540_project_4_v1.srcs/sources_1/ip/world_map/world_map_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'world_map'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
