# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/nexys4_ddr/mfp_nexys4_ddr.xdc

# IP: ip/rojobot31_0_1/rojobot31_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rojobot31_0 || ORIG_REF_NAME==rojobot31_0} -quiet] -quiet
