# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Final_Project_ECE540-bots_on_new_map_integration/ece_540_project_4_v1.srcs/sources_1/ip/map4/map4.xci
# IP: The module: 'map4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Final_Project_ECE540-bots_on_new_map_integration/ece_540_project_4_v1.srcs/sources_1/ip/map4/map4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'map4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Final_Project_ECE540-bots_on_new_map_integration/ece_540_project_4_v1.srcs/sources_1/ip/map4/map4.xci
# IP: The module: 'map4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Final_Project_ECE540-bots_on_new_map_integration/ece_540_project_4_v1.srcs/sources_1/ip/map4/map4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'map4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
